units_to_create = {
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 6780.6, y = 7113.9, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_1', group = '', rank = '城池/8', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 9182.5, y = 7039.8, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_2', group = '', rank = '城池/31', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 9246.9, y = 180.7, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_3', group = '', rank = '城池/34', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 6960.6, y = 148.5, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_4', group = '', rank = '城池/37', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 2903.1, y = 0.0, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_5', group = '', rank = '城池/40', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 3064.1, y = 6878.7, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_6', group = '', rank = '城池/43', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 9311.3, y = 13898.9, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_7', group = '', rank = '城池/46', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 9311.3, y = 19373.3, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_8', group = '', rank = '城池/49', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 6799.6, y = 14124.3, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_9', group = '', rank = '城池/52', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$default_units_ts.unit.星火战士.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 6735.2, y = 19147.8, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '[默认]近战英雄样例', node_mark = '城池_10', group = '', rank = '城池/55', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
    {name = '$$sjpx_lweb.unit.步兵.root', is_main_hero = 0, use_default_ai = '', team_id = 1, random_model_index = -1, position = {x = 11336.8, y = 16938.3, z = 0.0}, facing = 0, scale = {x = 1.0, y = 1.0, z = 1.0}, scene_path = '', custom_name = '步兵', node_mark = '城池_11', group = '', rank = '城池/137', is_item = false, item_link = '', description = '', invisible = '', unselectable = '', light_baked_enable = false, attribute = {}, },
}